version: '3.4'

services:
  microservices.posts.commands.api:
    image: ${DOCKER_REGISTRY-}microservicespostscommandsapi
    build:
      context: .
      dockerfile: Microservices.Posts.Commands.Api/Dockerfile
  microservices.posts.queries.api:
    image: ${DOCKER_REGISTRY-}microservicespostsqueriesapi
    build:
      context: .
      dockerfile: Microservices.Posts.Queries.Api/Dockerfile
  command-db:
    image: mongo
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2017-latest

volumes:
  mongo_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
